### ISSUE TITLE
Increase Font Family Options

### ISSUE THREAD

**Issue by HarshitSharma4** [HauseMasterZ/swift-type#10]
There is only few options available in font family.Should increase font family options

**Comment by HarshitSharma4** [comment]
assign this to me I want to work on this in hacktoberfest

**Comment by HauseMasterZ** [comment]
Assigned.

**Comment by HarshitSharma4** [comment]
I try to set up repository and showing me error:Uncaught FirebaseError: Firebase: Error (auth/invalid-api-key). 
please could help me with this.
![Screenshot from 2023-10-26 23-24-12](https://github.com/HauseMasterZ/swift-type/assets/106171546/3214a511-00bf-476f-a9d9-abeaca6c5c09)

**Comment by HauseMasterZ** [comment]
I think you didnt setup a .env.local file which has react environment variables. Anyways I've made some changes to the code it should now work without the .env file, try to pull the latest changes and try again.
